dp_platformuitypelist_typelist:
    path:     /dp/typelist/{sortMethod}/{sortOrder}/{typeIdentifier}
    defaults:
        sortMethod: "modified"
        sortOrder: "descending"
        typeIdentifier: ""
        _controller: dp.platformuitypelist.controller.typelist:listAction
    methods: [GET]
