parameters:
    dp.platformuitypelist.controller.typelist.class: DP\PlatformUITypeListBundle\Controller\TypeListController
services:
    dp.platformuitypelist.controller.typelist:
        class: %dp.platformuitypelist.controller.typelist.class%
        parent: ezpublish.controller.base
